language: c

arch:
  - amd64
  - arm64

compiler:
  - gcc
  - clang

# Ubuntu 18.04 LTS
dist: bionic

sudo: required

install:
- sudo apt-get -qq update
- sudo misc/install-deps.sh -y
- sudo apt install -y python3-pip
- python3 -m pip install pre-commit
- pre-commit install

script: pre-commit run -s HEAD~1 -o HEAD --show-diff-on-failure && ./configure && make ASAN=1 && make ASAN=1 unittest && (cd tests && ./runtest.py -O2 > /dev/null && cat failed-tests.txt)

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "zl83nEBIlkt3inI+jtGCDmrA3Lzdylf7Ez81soIPEWlirR2nZGfwhnHzfV8BCl+vaxaDIZYhHcHNF90Qt2WEOZ980WfXS0PPMslEWsL57N1oh2/5/dWHANL/+hlw11EiwtWNm6DEY4E2WyrCRinzxoVkH+UgKMV0cLPs5y5qMLd+/oqfDKD1eMp91GsEB+mzK7/qoS1H8TbubbyS3nFpUj9ZqsZwBGatL62vZYiTnaw+8M9BANFl/ctE9dchNNhKUYxwXMLKmE/ET7Ryk0Ikf1QojG0NI7xUyoZsVDifipYTWOIKJQWVxJwlyUE9QZsrYIVM/5qbeOlDKOwTtvOXW3joSlYrgNv5Bp3UJJAUxIrH5X45e1bi7TTiJ/KhT48+jTLtKp619PUuw23hlHKMK6p9niXcA/tNHCEnQTd8GuKOHV3ebAipeIBcuNTTmR4AnnzwB870UAFF9cS1YMAeW1wDXxO9w8CiwKnOlFRfko+YkC7H+DhuEn7Fg7nB6VoNCgCle5SUnTAbMIuH4TqlPI6ix9SHUU+jIWn+hS9Ck5vecGzvEglsOsiXsZ/dx3NzkEO35JFc4XhmCk9VQsOgJFgufC3vB2sG4cQML09PdbyPQ4XMuAgDB3EmjRwa6IiUuUuBqYqBSmZyhZOp3xBtAebg5MTz+fRQ+2ku/RM54gE="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name:                "namhyung/uftrace"
      description:         "Build submitted via Travis CI"
    notification_email:    namhyung@gmail.com
    build_command_prepend: "./configure; make clean"
    build_command:         "make -j 4"
    branch_pattern:        coverity_scan
